# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_buy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m', verbose_name='封面图'),
        ),
    ]
