# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180506_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
    ]
